# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/perolink.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "proto/perolink.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14proto/perolink.proto\x12\x08perolink"\xec\x02\n\x08\x45nvelope\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x11\n\ttarget_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12(\n\theartbeat\x18\n \x01(\x0b\x32\x13.perolink.HeartbeatH\x00\x12 \n\x05hello\x18\x0b \x01(\x0b\x32\x0f.perolink.HelloH\x00\x12\x30\n\x08register\x18\x0c \x01(\x0b\x32\x1c.perolink.CapabilityRegisterH\x00\x12*\n\x07request\x18\x14 \x01(\x0b\x32\x17.perolink.ActionRequestH\x00\x12,\n\x08response\x18\x15 \x01(\x0b\x32\x18.perolink.ActionResponseH\x00\x12&\n\x06stream\x18\x1e \x01(\x0b\x32\x14.perolink.DataStreamH\x00\x42\t\n\x07payload"\x18\n\tHeartbeat\x12\x0b\n\x03seq\x18\x01 \x01(\x03"U\n\x05Hello\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t"?\n\nCapability\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x03(\t"@\n\x12\x43\x61pabilityRegister\x12*\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32\x14.perolink.Capability"\x88\x01\n\rActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12\x33\n\x06params\x18\x02 \x03(\x0b\x32#.perolink.ActionRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"U\n\x0e\x41\x63tionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x11\n\terror_msg\x18\x04 \x01(\t"S\n\nDataStream\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06is_end\x18\x03 \x01(\x08\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\tB,Z*github.com/YoKONCy/PeroLink/proto;perolinkb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.perolink_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z*github.com/YoKONCy/PeroLink/proto;perolink"
    )
    _globals["_ACTIONREQUEST_PARAMSENTRY"]._loaded_options = None
    _globals["_ACTIONREQUEST_PARAMSENTRY"]._serialized_options = b"8\001"
    _globals["_ENVELOPE"]._serialized_start = 35
    _globals["_ENVELOPE"]._serialized_end = 399
    _globals["_HEARTBEAT"]._serialized_start = 401
    _globals["_HEARTBEAT"]._serialized_end = 425
    _globals["_HELLO"]._serialized_start = 427
    _globals["_HELLO"]._serialized_end = 512
    _globals["_CAPABILITY"]._serialized_start = 514
    _globals["_CAPABILITY"]._serialized_end = 577
    _globals["_CAPABILITYREGISTER"]._serialized_start = 579
    _globals["_CAPABILITYREGISTER"]._serialized_end = 643
    _globals["_ACTIONREQUEST"]._serialized_start = 646
    _globals["_ACTIONREQUEST"]._serialized_end = 782
    _globals["_ACTIONREQUEST_PARAMSENTRY"]._serialized_start = 737
    _globals["_ACTIONREQUEST_PARAMSENTRY"]._serialized_end = 782
    _globals["_ACTIONRESPONSE"]._serialized_start = 784
    _globals["_ACTIONRESPONSE"]._serialized_end = 869
    _globals["_DATASTREAM"]._serialized_start = 871
    _globals["_DATASTREAM"]._serialized_end = 954
# @@protoc_insertion_point(module_scope)
